// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_HelloWinUICppWinRT_0_H
#define WINRT_HelloWinUICppWinRT_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::HelloWinUICppWinRT
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<HelloWinUICppWinRT::IMainPage>{ using type = interface_category; };
    template <> struct category<HelloWinUICppWinRT::MainPage>{ using type = class_category; };
    template <> struct category<HelloWinUICppWinRT::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<HelloWinUICppWinRT::MainPage> = L"HelloWinUICppWinRT.MainPage";
    template <> inline constexpr auto& name_v<HelloWinUICppWinRT::XamlMetaDataProvider> = L"HelloWinUICppWinRT.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<HelloWinUICppWinRT::IMainPage> = L"HelloWinUICppWinRT.IMainPage";
    template <> inline constexpr guid guid_v<HelloWinUICppWinRT::IMainPage>{ 0x36F24982,0xFF24,0x5C0A,{ 0xA9,0x49,0x8A,0xB3,0x6B,0x37,0x24,0x3C } }; // 36F24982-FF24-5C0A-A949-8AB36B37243C
    template <> struct default_interface<HelloWinUICppWinRT::MainPage>{ using type = HelloWinUICppWinRT::IMainPage; };
    template <> struct default_interface<HelloWinUICppWinRT::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<HelloWinUICppWinRT::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_HelloWinUICppWinRT_IMainPage
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<HelloWinUICppWinRT::IMainPage>
    {
        template <typename D> using type = consume_HelloWinUICppWinRT_IMainPage<D>;
    };
}
#endif
