// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_Microsoft_UI_Xaml_Controls_Primitives_1_H
#define WINRT_Microsoft_UI_Xaml_Controls_Primitives_1_H
#include "winrt/impl/Microsoft.UI.Xaml.Controls.Primitives.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls::Primitives
{
    struct __declspec(empty_bases) IAutoSuggestBoxHelper :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoSuggestBoxHelper>
    {
        IAutoSuggestBoxHelper(std::nullptr_t = nullptr) noexcept {}
        IAutoSuggestBoxHelper(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutoSuggestBoxHelperStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoSuggestBoxHelperStatics>
    {
        IAutoSuggestBoxHelperStatics(std::nullptr_t = nullptr) noexcept {}
        IAutoSuggestBoxHelperStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSlider :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSlider>
    {
        IColorPickerSlider(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSlider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSliderFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSliderFactory>
    {
        IColorPickerSliderFactory(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSliderFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSliderStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSliderStatics>
    {
        IColorPickerSliderStatics(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSliderStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrum :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrum>
    {
        IColorSpectrum(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrum(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrumFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrumFactory>
    {
        IColorSpectrumFactory(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrumFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrumStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrumStatics>
    {
        IColorSpectrumStatics(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrumStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayout :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayout>
    {
        IColumnMajorUniformToLargestGridLayout(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayout(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayoutFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayoutFactory>
    {
        IColumnMajorUniformToLargestGridLayoutFactory(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayoutFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayoutStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayoutStatics>
    {
        IColumnMajorUniformToLargestGridLayoutStatics(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayoutStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IComboBoxHelper :
        Windows::Foundation::IInspectable,
        impl::consume_t<IComboBoxHelper>
    {
        IComboBoxHelper(std::nullptr_t = nullptr) noexcept {}
        IComboBoxHelper(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IComboBoxHelperStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IComboBoxHelperStatics>
    {
        IComboBoxHelperStatics(std::nullptr_t = nullptr) noexcept {}
        IComboBoxHelperStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBar :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBar>
    {
        ICommandBarFlyoutCommandBar(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBar(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBarFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBarFactory>
    {
        ICommandBarFlyoutCommandBarFactory(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBarFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBarTemplateSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBarTemplateSettings>
    {
        ICommandBarFlyoutCommandBarTemplateSettings(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBarTemplateSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusFilterConverter :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusFilterConverter>
    {
        ICornerRadiusFilterConverter(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusFilterConverter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusFilterConverterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusFilterConverterStatics>
    {
        ICornerRadiusFilterConverterStatics(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusFilterConverterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusToThicknessConverter :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusToThicknessConverter>
    {
        ICornerRadiusToThicknessConverter(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusToThicknessConverter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusToThicknessConverterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusToThicknessConverterStatics>
    {
        ICornerRadiusToThicknessConverterStatics(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusToThicknessConverterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenter :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenter>
    {
        INavigationViewItemPresenter(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenterFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenterFactory>
    {
        INavigationViewItemPresenterFactory(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenterFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenterStatics>
    {
        INavigationViewItemPresenterStatics(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITabViewListView :
        Windows::Foundation::IInspectable,
        impl::consume_t<ITabViewListView>
    {
        ITabViewListView(std::nullptr_t = nullptr) noexcept {}
        ITabViewListView(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITabViewListViewFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ITabViewListViewFactory>
    {
        ITabViewListViewFactory(std::nullptr_t = nullptr) noexcept {}
        ITabViewListViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
