service: serverless-bolt-sample

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  events:
    handler: handler.app
    timeout: 30
    events:
      # Bolt App
      - http:
          method: post
          path: /slack/events
      # OAuth Flow
      - http:
          method: get
          path: /slack/installation
      - http:
          method: get
          path: /slack/oauth

plugins:
  - serverless-offline
