// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#pragma once
#include "winrt/HelloWinUICppWinRT.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
namespace winrt::HelloWinUICppWinRT::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProvider_base : implements<D, HelloWinUICppWinRT::XamlMetaDataProvider, I...>
    {
        using base_type = XamlMetaDataProvider_base;
        using class_type = HelloWinUICppWinRT::XamlMetaDataProvider;
        using implements_type = typename XamlMetaDataProvider_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"HelloWinUICppWinRT.XamlMetaDataProvider";
        }
    };
}
namespace winrt::HelloWinUICppWinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProviderT : implements<D, Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = HelloWinUICppWinRT::XamlMetaDataProvider;

        hstring GetRuntimeClassName() const
        {
            return L"HelloWinUICppWinRT.XamlMetaDataProvider";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_XAMLMETADATAPROVIDER_XAML_G_H) || __has_include("XamlMetaDataProvider.xaml.g.h")
#include "XamlMetaDataProvider.xaml.g.h"
#else

namespace winrt::HelloWinUICppWinRT::implementation
{
    template <typename D, typename... I>
    using XamlMetaDataProviderT = XamlMetaDataProvider_base<D, I...>;
}

#endif
