// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

void* winrt_make_HelloWinUICppWinRT_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::HelloWinUICppWinRT::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::HelloWinUICppWinRT
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<HelloWinUICppWinRT::implementation::XamlMetaDataProvider>())
    {
    }
}
