// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_HelloWinUICppWinRT_H
#define WINRT_HelloWinUICppWinRT_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.200703.9"), "Mismatched C++/WinRT headers.");
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/HelloWinUICppWinRT.2.h"
namespace winrt::impl
{
    template <typename D> WINRT_IMPL_AUTO(int32_t) consume_HelloWinUICppWinRT_IMainPage<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(HelloWinUICppWinRT::IMainPage)->get_MyProperty(&value));
        return value;
    }
    template <typename D> WINRT_IMPL_AUTO(void) consume_HelloWinUICppWinRT_IMainPage<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(HelloWinUICppWinRT::IMainPage)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, HelloWinUICppWinRT::IMainPage> : produce_base<D, HelloWinUICppWinRT::IMainPage>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::HelloWinUICppWinRT
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::HelloWinUICppWinRT::IMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HelloWinUICppWinRT::MainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HelloWinUICppWinRT::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
}
#endif
