version: '3.7'
services:

  test:
    image: test_app:latest
    build:
      context: ./../../
      dockerfile: ./share/docker/test.Dockerfile
    container_name: test
    depends_on:
      - server
    env_file:
      - ./../env/test.env
    working_dir: /usr/src/workspace
    command: cargo test -- --nocapture

  # 80 ポートは公開しなくてもOK
  server:
    image: nginx:1.25.1
    container_name: server
