# 下記のコマンドで取得したものを指定する
# minikube kubectl api-resources
# 誤った指定だと下記のようなエラーが発生する
# error: resource mapping not found for name: "piyo-app" namespace: "" from "./deployment.yaml": no matches for kind "Deployment" in version "v1"
apiVersion: apps/v1

kind: Deployment
metadata:
  name: piyo-app
  labels:
    app: piyo
spec:
  selector:
    matchLabels:
      app: piyo
  replicas: 4

  # Pod
  template:
    metadata:
      labels:
        app: piyo
    spec:
      containers:
        - name: piyo-container
          image: nginx:1.23.3
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: piyo-app
  labels:
    app: piyo
spec:
  type: NodePort
  selector:
    app: piyo
  ports:
    - name: '8080-80'
      port: 8080
      targetPort: 80
