services:
  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - 3000:3000
    volumes:
      - ./share/dashboards/:/var/lib/grafana/dashboards/
      - ./share/provisionings/:/etc/grafana/provisioning/
    networks:
      - default

  loki:
    image: grafana/loki:3.4.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
