service: serverless-framework

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
    environment:
      SAMPLE_VALUE: Sample

plugins:
    - serverless-offline
